Repository openstax/tutor-js, pull requests merged in 2018-07, with the labels that each got.

#2263 re-enable physics highlighting
  tutor/resources/styles/components/annotations/annotation.scss
  tutor/specs/components/__snapshots__/annotations.spec.jsx.snap
  tutor/specs/components/annotations.spec.jsx
  tutor/specs/models/course.spec.js
  tutor/src/components/annotations/annotation-card.jsx
  tutor/src/components/annotations/annotation.jsx
  tutor/src/components/annotations/highlighter.js
  tutor/src/helpers/dom.js
  tutor/src/models/course.js
Labels: Next Release

#2279 update wording on cloned course tour to include mention of LMS
  tutor/src/tours/new-enrollment-link.json
Labels: needs review

#2278 only name and other info from source course if it's clonable
  tutor/specs/models/courses/create.spec.js
  tutor/specs/screens/new-course/course-numbers.spec.jsx
  tutor/specs/screens/new-course/ux.spec.js
  tutor/src/models/course/create.js
Labels: needs review

#2277 correct "Contact Support" link on manage payments
  tutor/specs/components/payments/__snapshots__/manage.spec.jsx.snap
  tutor/src/components/payments/manage.jsx
Labels: needs review

#2275 Fix controls not pinning in safari
  shared/specs/components/pinned-header-footer-card/index.spec.cjsx
  shared/src/components/pinned-header-footer-card/index.cjsx
  shared/src/components/scroll-tracker.cjsx
  shared/src/mixins/ScrollListener.js
  tutor/resources/styles/components/exercises.scss
  tutor/resources/styles/mixins/exercise-cards-column-layout.scss
  tutor/resources/styles/tutor.scss
  tutor/specs/models/exercises.spec.js
  tutor/specs/screens/question-library/__snapshots__/dashboard.spec.jsx.snap
  tutor/src/components/exercises/cards.jsx
  tutor/src/components/exercises/no-exercises-found.cjsx
  tutor/src/components/exercises/no-exercises-found.jsx
  tutor/src/components/task-plan/homework/add-exercises.jsx
  tutor/src/components/task-plan/homework/choose-exercises.jsx
  tutor/src/models/exercises.js
  tutor/src/screens/question-library/exercise-controls.jsx
  tutor/src/screens/question-library/exercises-display.jsx
  tutor/src/screens/question-library/index.jsx
  tutor/src/screens/question-library/no-exercises-found.jsx
  tutor/src/screens/question-library/styles.scss
Labels: needs review

#2276 add open-ended format
  exercises/specs/components/__snapshots__/exercise.spec.js.snap
  shared/specs/model/exercise/answer.spec.js
  shared/specs/model/exercise/question.spec.js
  shared/src/model/exercise.js
  shared/src/model/exercise/answer.js
  shared/src/model/exercise/question.js
Labels: exercises, needs review

#2285 handle long content in error modal
  tutor/resources/styles/components/tutor-dialog.scss
Labels: Next Release

#2295 Fixes for exercise editing
  exercises/specs/components/__snapshots__/exercise.spec.js.snap
  exercises/specs/components/exercise.spec.js
  exercises/specs/components/exercise/__snapshots__/controls.spec.js.snap
  exercises/specs/components/exercise/controls.spec.js
  exercises/src/app.jsx
  exercises/src/components/exercise/controls.jsx
  exercises/src/models/exercises.js
  shared/specs/factories/exercise.js
  shared/src/model/exercise.js
  shared/src/model/exercise/question.js
  shared/src/model/exercise/solution.js
Labels: exercises, needs review
