Repository openstax/tutor-js, pull requests merged in 2018-03, with the labels that each got.

#2151 correct scss function from fadeout to be correct "fade-out"
  screenshots/teacher-my-courses-pending-verification.png
  tutor/resources/styles/components/my-courses.scss
  tutor/resources/styles/components/task/index.scss
  tutor/specs/acceptance/my-courses.spec.js
Labels: needs review

#2152 Fix re-exporting default exports from JS
  shared/src/helpers/task.js
  shared/src/index.js
Labels: needs review

#2153 Fix scores report message for students with no assignments
  tutor/specs/screens/scores-report/index.spec.jsx
  tutor/src/screens/scores-report/table.jsx
Labels: needs review

#2149 Don't re-use default value, instead always start with ''
  tutor/src/components/course-roster/add-period.jsx
Labels: needs review

#2150 Fix fetching tasks on enrollment
  tutor/specs/components/helpers/component-testing.coffee
  tutor/specs/models/courses/onboarding/student-course.spec.js
  tutor/specs/screens/student-dashboard/dashboard.spec.jsx
  tutor/src/models/course/onboarding/student-course.js
  tutor/src/models/student-tasks.js
  tutor/src/screens/student-dashboard/empty-panel.jsx
  tutor/src/screens/student-dashboard/index.jsx
Labels: needs review

#2145 Fix scores moar
  shared/src/api/action-adapter.coffee
  tutor/resources/styles/global/buttons.scss
  tutor/specs/screens/scores-report/summary-columns.spec.js
  tutor/src/components/error-monitoring/async-load-error.jsx
  tutor/src/flux/app.coffee
  tutor/src/screens/scores-report/overall-cell.jsx
  tutor/src/screens/scores-report/set-weights-modal.jsx
  tutor/src/screens/scores-report/styles.scss
  tutor/src/screens/scores-report/styles/overall-cell.scss
  tutor/src/screens/scores-report/styles/set-weights-modal.scss
  tutor/src/screens/scores-report/ux.js
  tutor/src/screens/scores-report/weights-ux.jsx
Labels: needs review

#2154 Fix QA view for APUSH & Bio, add book content
  package.json
  tutor/resources/styles/book-content/mixins.scss
  tutor/resources/styles/book-content/note.scss
  tutor/resources/styles/book-content/page.scss
  tutor/resources/styles/components/book-menu.scss
  tutor/resources/styles/global/externals.scss
  tutor/resources/styles/variables.scss
  tutor/specs/screens/__snapshots__/qa-view.spec.jsx.snap
  tutor/specs/screens/__snapshots__/qa.spec.jsx.snap
  tutor/specs/screens/__snapshots__/reference-book.spec.js.snap
  tutor/specs/screens/qa-view.spec.jsx
  tutor/specs/screens/reference-book.spec.js
  tutor/src/components/book-content-mixin.cjsx
  tutor/src/components/book-page.cjsx
  tutor/src/components/book-page/exercise.jsx
  tutor/src/routes.js
  tutor/src/screens/qa-view/ecosystem-selector.jsx
  tutor/src/screens/qa-view/exercise-card.jsx
  tutor/src/screens/qa-view/exercises.jsx
  tutor/src/screens/qa-view/index.jsx
  tutor/src/screens/qa-view/styles.scss
  tutor/src/screens/qa-view/ux.js
  tutor/src/screens/qa-view/view-toggle.jsx
  tutor/src/screens/qa-view/view.jsx
  tutor/src/screens/reference-book/page-navigation.jsx
  tutor/src/screens/reference-book/reference-book.jsx
  tutor/src/screens/reference-book/styles.scss
  tutor/src/screens/reference-book/ux.js
  yarn.lock
Labels: needs review

#2155 Replace performance report links with BackButton
  tutor/src/components/performance-forecast/student.cjsx
  tutor/src/components/performance-forecast/teacher-student.cjsx
  tutor/src/components/performance-forecast/teacher.cjsx
Labels: needs review

#2157 weight inputs were not observing weight updates, so the input would …
  tutor/src/screens/scores-report/set-weights-modal.jsx
Labels: needs review

#2159 move closing modal to more immediate, allow blank weights so backspae…
  tutor/src/screens/scores-report/set-weights-modal.jsx
  tutor/src/screens/scores-report/weights-ux.js
Labels: needs review

#2156 Fix scores null averages
  tutor/index.js
  tutor/src/models/course/task-plans.js
  tutor/src/models/task-plan/teacher.js
  tutor/src/models/tasking-plan.js
  tutor/src/screens/scores-report/overall-cell.jsx
  tutor/src/screens/scores-report/overall-header.jsx
  tutor/src/screens/scores-report/table.jsx
  tutor/src/screens/scores-report/ux.js
  tutor/src/screens/scores-report/weights-ux.js
Labels: needs review

#2161 Display correct / progress for readings & homeworks
  tutor/specs/components/tours/region.spec.jsx
  tutor/specs/screens/scores-report/__snapshots__/pie-progress.spec.jsx.snap
  tutor/specs/screens/scores-report/homework-cell.spec.jsx
  tutor/specs/screens/scores-report/pie-progress.spec.jsx
  tutor/specs/screens/scores-report/reading-cell.spec.jsx
  tutor/src/models/course/scores.js
  tutor/src/screens/scores-report/homework-cell.jsx
  tutor/src/screens/scores-report/late-work.jsx
  tutor/src/screens/scores-report/percent-correct.jsx
  tutor/src/screens/scores-report/percent.jsx
  tutor/src/screens/scores-report/pie-progress.jsx
  tutor/src/screens/scores-report/reading-cell.jsx
  tutor/src/screens/scores-report/styles/table.scss
Labels: needs review

#2162 when percent was actually 0, null was being returned for average
  tutor/src/screens/scores-report/ux.js
Labels: needs review

#2165 Scores warning triangle
  tutor/specs/screens/scores-report/index.spec.jsx
  tutor/specs/screens/scores-report/ux.spec.js
  tutor/src/models/course/scores.js
  tutor/src/screens/scores-report/overall-header.jsx
  tutor/src/screens/scores-report/styles/overall-cell.scss
  tutor/src/screens/scores-report/table.jsx
  tutor/src/screens/scores-report/ux.js
Labels: needs review

#2170 update factory and moment
  package.json
  yarn.lock
Labels: needs review

#2169 Prompt users to reload after a deployment
  shared/src/model/notifications.coffee
  tutor/index.js
  tutor/resources/styles/components/toasts.scss
  tutor/resources/styles/components/top-nav-bar.scss
  tutor/resources/styles/tutor.scss
  tutor/specs/components/navbar/background-toasts.spec.jsx
  tutor/specs/components/navbar/toasts/__snapshots__/lms.spec.js.snap
  tutor/specs/components/toasts/__snapshots__/lms.spec.js.snap
  tutor/specs/components/toasts/lms.spec.js
  tutor/specs/components/toasts/scores.spec.js
  tutor/specs/factories/exercise.js
  tutor/specs/helpers/reload.spec.js
  tutor/specs/models/app.spec.js
  tutor/specs/models/jobs/lms-score-push.spec.js
  tutor/specs/models/jobs/scores-export.spec.js
  tutor/specs/screens/question-library/dashboard.spec.jsx
  tutor/src/api/index.coffee
  tutor/src/components/navbar/background-toasts.jsx
  tutor/src/components/toasts/lms.jsx
  tutor/src/components/toasts/reload.jsx
  tutor/src/components/toasts/scores.jsx
  tutor/src/flux/notifications.coffee
  tutor/src/helpers/reload.js
  tutor/src/models/app.js
  tutor/src/models/jobs/lms-score-push.js
  tutor/src/models/jobs/queue.js
  tutor/src/models/jobs/scores-export.js
  tutor/src/models/toasts.js
  tutor/src/screens/scores-report/homework-cell.jsx
Labels: needs review

#2158 release 2018-03-12
  tutor/index.js
  tutor/specs/components/tours/region.spec.jsx
  tutor/specs/screens/scores-report/__snapshots__/assignment-header.spec.jsx.snap
  tutor/specs/screens/scores-report/__snapshots__/pie-progress.spec.jsx.snap
  tutor/specs/screens/scores-report/homework-cell.spec.jsx
  tutor/specs/screens/scores-report/index.spec.jsx
  tutor/specs/screens/scores-report/pie-progress.spec.jsx
  tutor/specs/screens/scores-report/reading-cell.spec.jsx
  tutor/specs/screens/scores-report/ux.spec.js
  tutor/src/models/course/scores.js
  tutor/src/models/course/task-plans.js
  tutor/src/models/task-plan/teacher.js
  tutor/src/models/tasking-plan.js
  tutor/src/screens/scores-report/assignment-header.jsx
  tutor/src/screens/scores-report/homework-cell.jsx
  tutor/src/screens/scores-report/late-work.jsx
  tutor/src/screens/scores-report/overall-cell.jsx
  tutor/src/screens/scores-report/overall-header.jsx
  tutor/src/screens/scores-report/percent-correct.jsx
  tutor/src/screens/scores-report/percent.jsx
  tutor/src/screens/scores-report/pie-progress.jsx
  tutor/src/screens/scores-report/reading-cell.jsx
  tutor/src/screens/scores-report/set-weights-modal.jsx
  tutor/src/screens/scores-report/styles/overall-cell.scss
  tutor/src/screens/scores-report/styles/table.scss
  tutor/src/screens/scores-report/table.jsx
  tutor/src/screens/scores-report/ux.js
  tutor/src/screens/scores-report/weights-ux.js
Labels: Next Release

#2175 Highlighting updates
  tutor/resources/styles/components/annotations/annotation.scss
  tutor/resources/styles/components/annotations/summary-page.scss
  tutor/resources/styles/mixins.scss
  tutor/resources/styles/mixins/triangle.scss
  tutor/specs/components/__snapshots__/annotations.spec.jsx.snap
  tutor/src/components/annotations/annotation-card.jsx
  tutor/src/components/annotations/annotation.jsx
  tutor/src/components/annotations/inline-controls.jsx
  tutor/src/components/annotations/sidebar-buttons.jsx
  tutor/src/components/annotations/summary-page.jsx
  tutor/src/models/course.js
Labels: needs review

#2171 Style research surveys
  bin/screenshot
  package.json
  screenshots/student-dashboard-past-work.png
  screenshots/student-dashboard-tip-1.png
  screenshots/student-dashboard-tip-2.png
  screenshots/student-dashboard-tip-3.png
  screenshots/student-dashboard-tip-4.png
  screenshots/student-dashboard-tip-5.png
  screenshots/student-dashboard-tip-6.png
  screenshots/student-dashboard-tip-7.png
  screenshots/student-dashboard.png
  screenshots/student-survey.png
  screenshots/teacher-my-courses.png
  shared/src/index.js
  tutor/api/research_survey.json
  tutor/index.html
  tutor/resources/styles/components/course-page.scss
  tutor/specs/acceptance/dashboard.spec.js
  tutor/specs/acceptance/server/backend.js
  tutor/specs/acceptance/server/backend/bootstrap.js
  tutor/specs/acceptance/server/backend/dashboard.js
  tutor/specs/acceptance/server/backend/db.json
  tutor/specs/acceptance/server/backend/performance-forecast.js
  tutor/specs/acceptance/server/backend/previous-plans.js
  tutor/specs/acceptance/server/index.js
  tutor/specs/acceptance/server/ports.js
  tutor/specs/acceptance/server/time-now.js
  tutor/specs/acceptance/survey.spec.js
  tutor/specs/factories/book.js
  tutor/specs/factories/course.js
  tutor/specs/factories/dashboard.js
  tutor/specs/factories/helpers.js
  tutor/specs/factories/index.js
  tutor/specs/factories/performance-forecast.js
  tutor/specs/factories/research_survey.js
  tutor/specs/models/student-tasks.spec.jsx
  tutor/specs/screens/__snapshots__/surveys.spec.js.snap
  tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
  tutor/specs/screens/surveys.spec.js
  tutor/src/models/student-tasks.js
  tutor/src/screens/student-dashboard/dashboard.jsx
  tutor/src/screens/student-dashboard/styles/panel.scss
  tutor/src/screens/student-dashboard/styles/progress-guide.scss
  tutor/src/screens/student-dashboard/upcoming-panel.jsx
  tutor/src/screens/surveys/index.jsx
  tutor/src/screens/surveys/styles.scss
  yarn.lock
Labels: needs review

#2172 Add small score header specs
  tutor/specs/screens/scores-report/assignment-header.spec.jsx
  tutor/src/screens/scores-report/assignment-header.jsx
Labels: needs review

#2178 Fix NaN% and percent / progress display toggle on scores
  tutor/api/courses/1/performance.json
  tutor/specs/screens/scores-report/homework-cell.spec.jsx
  tutor/specs/screens/scores-report/reading-cell.spec.jsx
  tutor/specs/screens/scores-report/ux.spec.js
  tutor/src/helpers/task.coffee
  tutor/src/models/course/scores/task-result.js
  tutor/src/screens/scores-report/assignment-cell.jsx
  tutor/src/screens/scores-report/assignment-header.jsx
  tutor/src/screens/scores-report/correctness-value.jsx
  tutor/src/screens/scores-report/export-controls.jsx
  tutor/src/screens/scores-report/external-cell.jsx
  tutor/src/screens/scores-report/homework-cell.jsx
  tutor/src/screens/scores-report/index.jsx
  tutor/src/screens/scores-report/percent.jsx
  tutor/src/screens/scores-report/reading-cell.jsx
  tutor/src/screens/scores-report/styles/controls.scss
  tutor/src/screens/scores-report/styles/table.scss
  tutor/src/screens/scores-report/table-filters.jsx
  tutor/src/screens/scores-report/table.jsx
  tutor/src/screens/scores-report/ux.js
Labels: needs review

#2179 Fix weird top margin and scroll to linked annotation
  tutor/resources/styles/components/annotations/summary-page.scss
  tutor/specs/components/__snapshots__/annotations.spec.jsx.snap
  tutor/specs/components/annotations.spec.jsx
  tutor/src/components/annotations/annotation-card.jsx
  tutor/src/components/annotations/annotation.jsx
Labels: needs review

#2174 record and use osweb_base_url
  shared/specs/helpers/exercise.spec.js
  shared/src/helpers/exercise.js
  tutor/src/models/app.js
Labels: needs review, ✓ reviewed

#2180 Only fast poll if the course has tasks available
  tutor/specs/components/enroll.spec.jsx
  tutor/specs/factories/index.js
  tutor/specs/models/courses/enroll.spec.js
  tutor/specs/models/courses/onboarding/student-course.spec.js
  tutor/src/models/course/enroll.js
  tutor/src/models/course/onboarding/student-course.js
  tutor/src/models/courses-map.js
  tutor/src/models/student-tasks.js
  tutor/src/models/user.js
Labels: needs review

#2182 close highlight summary window shade when esc key is pressed
  tutor/specs/components/annotations.spec.jsx
  tutor/src/components/annotations/annotation.jsx
  tutor/src/components/annotations/summary-page.jsx
  tutor/src/components/annotations/window-shade.jsx
Labels: needs review

#2181 update back button colors
  tutor/specs/components/navbar/spec-test-params.js
  tutor/specs/components/payments/__snapshots__/manage.spec.jsx.snap
  tutor/specs/components/student-preview/__snapshots__/index.spec.jsx.snap
  tutor/specs/components/task-teacher-review/__snapshots__/breadcrumbs.spec.jsx.snap
  tutor/specs/screens/question-library/__snapshots__/dashboard.spec.jsx.snap
  tutor/src/components/buttons/back-button.cjsx
  tutor/src/components/performance-forecast/teacher-student.cjsx
  tutor/src/helpers/routes-and-destinations.coffee
Labels: needs review

#2184 Don't load annotations when feature flag is off
  tutor/specs/models/annotations.spec.js
  tutor/src/models/annotations.js
Labels: needs review

#2187 Fix student dashboard past events to list all events
  tutor/specs/models/student-tasks.spec.jsx
  tutor/src/models/student-tasks.js
Labels: Next Release, needs review

#2186 use index for finding student's score not identifier
  tutor/specs/screens/scores-report/__snapshots__/overall-cell.spec.jsx.snap
  tutor/specs/screens/scores-report/overall-cell.spec.jsx
  tutor/src/screens/scores-report/overall-cell.jsx
Labels: Next Release, needs review

#2190 load exercises from course endpoint for QL
  tutor/specs/models/exercises.spec.js
  tutor/specs/screens/question-library/dashboard.spec.jsx
  tutor/src/models/exercises.js
  tutor/src/screens/question-library/sections-chooser.jsx
Labels: needs review

#2192 Scores report late external popover, reword external clicked heading
  tutor/api/courses/1/performance.json
  tutor/specs/models/courses/scores.spec.js
  tutor/specs/screens/scores-report/assignment-header.spec.jsx
  tutor/specs/screens/scores-report/external-cell.spec.jsx
  tutor/specs/screens/scores-report/student-data-sorter.spec.js
  tutor/src/components/late-icon.cjsx
  tutor/src/models/course/scores/task-result.js
  tutor/src/screens/scores-report/assignment-header.jsx
Labels: needs review

#2193 Adjust images
  tutor/resources/styles/book-content/base.scss
  tutor/resources/styles/book-content/page.scss
  tutor/src/components/book-content-mixin.cjsx
Labels: needs review

#2197 Disable highlighting for physics
  tutor/specs/models/course.spec.js
  tutor/src/models/course.js
Labels: Next Release, needs review

#2198 Fix "Waiting for page to load.." message for pages with no images
  tutor/specs/helpers/images-complete.spec.js
  tutor/src/components/annotations/annotation.jsx
  tutor/src/helpers/images-complete.js
Labels: Next Release, needs review

#2199 Hide excluded exercises on HW builder
  tutor/specs/components/task-plan/homework/choose-exercises.spec.js
  tutor/specs/models/exercises.spec.js
  tutor/src/components/task-plan/homework/choose-exercises.jsx
  tutor/src/models/exercises.js
  tutor/src/models/exercises/exercise.js
Labels: Next Release, needs review

#2202 Fix styles for menu changing after viewing surveys
  tutor/src/screens/surveys/styles.scss
Labels: Next Release, needs review

#2196 Include courseId when linking to preview video page
  tutor/specs/components/navbar/support-menu.spec.jsx
  tutor/src/components/navbar/support-menu.jsx
Labels: needs review

#2195 only cache webpack when cache ENV is set
  configs/webpack/base.coffee
  package.json
Labels: needs review

#2204 Fix survey range and misc styles
  tutor/specs/screens/__snapshots__/surveys.spec.js.snap
  tutor/src/screens/student-dashboard/surveys.jsx
  tutor/src/screens/surveys/index.jsx
  tutor/src/screens/surveys/styles.scss
Labels: needs review
