Repository openstax/tutor-js, pull requests merged in 2019-08, with the labels that each got.

#2682 Fix blank terms being displayed
  tutor/specs/components/terms-modal.spec.jsx
  tutor/src/components/terms-modal.jsx
Labels: bug

#2689 Fix nags
  tutor/resources/styles/global/menus.scss
  tutor/specs/components/__snapshots__/app.spec.jsx.snap
  tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
  tutor/specs/components/course-nag.spec.jsx
  tutor/specs/components/modal-manager.spec.jsx
  tutor/specs/components/navbar/__snapshots__/support-menu.spec.jsx.snap
  tutor/specs/components/navbar/support-menu.spec.jsx
  tutor/specs/components/onboarding/__snapshots__/freshly-created-course.spec.jsx.snap
  tutor/specs/components/onboarding/freshly-created-course.spec.jsx
  tutor/specs/components/terms-modal.spec.jsx
  tutor/specs/components/tours/conductor.spec.jsx
  tutor/specs/components/tutor-layout.spec.js
  tutor/specs/helpers/context.js
  tutor/specs/models/courses/onboarding/full-course.spec.js
  tutor/specs/models/courses/onboarding/index.spec.js
  tutor/specs/models/tour.spec.js
  tutor/specs/models/window-size.spec.js
  tutor/specs/screens/assignment-builder/homework/__snapshots__/exercises-table.spec.js.snap
  tutor/specs/screens/assignment-builder/homework/__snapshots__/review-exercises.spec.js.snap
  tutor/specs/screens/new-course/index.spec.jsx
  tutor/src/components/app.jsx
  tutor/src/components/course-nag.js
  tutor/src/components/exercises/details.jsx
  tutor/src/components/modal-manager.jsx
  tutor/src/components/navbar/support-menu.jsx
  tutor/src/components/terms-modal.jsx
  tutor/src/components/tours/conductor.jsx
  tutor/src/models/course/onboarding/base.js
  tutor/src/models/course/onboarding/full-course.js
  tutor/src/models/course/onboarding/index.js
  tutor/src/models/course/onboarding/preview.js
  tutor/src/models/course/onboarding/student-course.js
  tutor/src/models/tour.js
  tutor/src/models/tour/context.js
  tutor/src/models/tour/ride.js
Labels: bug, change

#2692 Display the terms of use faster
  tutor/specs/models/user.spec.js
  tutor/src/models/user.js
  tutor/src/screens/student-dashboard/index.jsx
  tutor/src/screens/teacher-dashboard/index.jsx
Labels: bug

#2704 Clear ui settings when ui_settings_is_too_long error occurs
  shared/src/model/networking.js
  shared/src/model/ui-settings.js
Labels: bug

#2712 Display ready tasks as the dashboard loads
  tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
  tutor/specs/screens/student-dashboard/dashboard.spec.jsx
  tutor/specs/screens/student-dashboard/empty-panel.spec.js
  tutor/specs/screens/student-dashboard/this-week-panel.spec.js
  tutor/src/models/task-plans/student.js
  tutor/src/screens/student-dashboard/all-events-by-week.jsx
  tutor/src/screens/student-dashboard/dashboard.jsx
  tutor/src/screens/student-dashboard/empty-panel.jsx
  tutor/src/screens/student-dashboard/events-panel.jsx
  tutor/src/screens/student-dashboard/late-icon-ledgend.js
  tutor/src/screens/student-dashboard/styles/empty-card.scss
  tutor/src/screens/student-dashboard/this-week-panel.jsx
  tutor/src/screens/student-dashboard/upcoming-panel.jsx
Labels: change
